# Track.destroy_all
Album.destroy_all
Artist.destroy_all

# Genre.destroy_all
# Customer.destroy_all
# Invoice.destroy_all
# InvoiceLine.destroy_all
# Playlist.destroy_all
# MediaType.destroy_all

Artist.create!([
                   {name: "AC/DC"},
                  {name: "Accept"},
                   {name: "Aerosmith"},
                   {name: "Alanis Morissette"},
                   {name: "Alice In Chains"},
                   {name: "Antnio Carlos Jobim"},
                   {name: "Apocalyptica"},
                   {name: "Audioslave"},
                   {name: "BackBeat"},
                   {name: "Billy Cobham"},
                   {name: "Black Label Society"},
                   {name: "Black Sabbath"},
                   {name: "Body Count"},
                   {name: "Bruce Dickinson"},
                   {name: "Buddy Guy"},
                   {name: "Caetano Veloso"},
                   {name: "Chico Buarque"},
                   {name: "Chico Science & Nao Zumbi"},
                   {name: "Cidade Negra"},
                   {name: "Cludio Zoli"},
                   {name: "Various Artists"},
                   {name: "Led Zeppelin"},
                   {name: "Frank Zappa & Captain Beefheart"},
                   {name: "Marcos Valle"},
                   {name: "Milton Nascimento & Bebeto"},
                   {name: "Azymuth"},
                   {name: "Gilberto Gil"},
                   {name: "Joo Gilberto"},
                   {name: "Bebel Gilberto"},
                   {name: "Jorge Vercilo"},
                   {name: "Baby Consuelo"},
                   {name: "Ney Matogrosso"},
                   {name: "Luiz Melodia"},
                   {name: "Nando Reis"},
                   {name: "Pedro Lus & A Parede"},
                   {name: "O Rappa"},
                   {name: "Ed Motta"},
                   {name: "Banda Black Rio"},
                   {name: "Fernanda Porto"},
                   {name: "Os Cariocas"},
                   {name: "Elis Regina"},
                   {name: "Milton Nascimento"},
                   {name: "A Cor Do Som"},
                   {name: "Kid Abelha"},
                   {name: "Sandra De S"},
                   {name: "Jorge Ben"},
                   {name: "Hermeto Pascoal"},
                   {name: "Baro Vermelho"},
                   {name: "Edson, DJ Marky & DJ Patife Featuring Fernanda Porto"},
                   {name: "Metallica"},
                   {name: "Queen"},
                   {name: "Kiss"},
                   {name: "Spyro Gyra"},
                   {name: "Green Day"},
                   {name: "David Coverdale"},
                   {name: "Gonzaguinha"},
                   {name: "Os Mutantes"},
                   {name: "Deep Purple"},
                   {name: "Santana"},
                   {name: "Santana Feat. Dave Matthews"},
                   {name: "Santana Feat. Everlast"},
                   {name: "Santana Feat. Rob Thomas"},
                   {name: "Santana Feat. Lauryn Hill & Cee-Lo"},
                   {name: "Santana Feat. The Project G&B"},
                   {name: "Santana Feat. Man"},
                   {name: "Santana Feat. Eagle-Eye Cherry"},
                   {name: "Santana Feat. Eric Clapton"},
                   {name: "Miles Davis"},
                   {name: "Gene Krupa"},
                   {name: "Toquinho & Vincius"},
                   {name: "Vincius De Moraes & Baden Powell"},
                   {name: "Vincius De Moraes"},
                   {name: "Vincius E Qurteto Em Cy"},
                   {name: "Vincius E Odette Lara"},
                   {name: "Vinicius, Toquinho & Quarteto Em Cy"},
                   {name: "Creedence Clearwater Revival"},
                   {name: "Cssia Eller"},
                   {name: "Def Leppard"},
                   {name: "Dennis Chambers"},
                   {name: "Djavan"},
                   {name: "Eric Clapton"},
                   {name: "Faith No More"},
                   {name: "Falamansa"},
                   {name: "Foo Fighters"},
                   {name: "Frank Sinatra"},
                   {name: "Funk Como Le Gusta"},
                   {name: "Godsmack"},
                   {name: "Guns N' Roses"},
                   {name: "Incognito"},
                   {name: "Iron Maiden"},
                   {name: "James Brown"},
                   {name: "Jamiroquai"},
                   {name: "JET"},
                   {name: "Jimi Hendrix"},
                   {name: "Joe Satriani"},
                   {name: "Jota Quest"},
                   {name: "Joo Suplicy"},
                   {name: "Judas Priest"},
                   {name: "Legio Urbana"},
                   {name: "Lenny Kravitz"},
                   {name: "Lulu Santos"},
                   {name: "Marillion"},
                   {name: "Marisa Monte"},
                   {name: "Marvin Gaye"},
                   {name: "Men At Work"},
                   {name: "Motrhead"},
                   {name: "Motrhead & Girlschool"},
                   {name: "Mnica Marianno"},
                   {name: "Mtley Cre"},
                   {name: "Nirvana"},
                   {name: "O Tero"},
                   {name: "Olodum"},
                   {name: "Os Paralamas Do Sucesso"},
                   {name: "Ozzy Osbourne"},
                   {name: "Page & Plant"},
                   {name: "Passengers"},
                   {name: "Paul D'Ianno"},
                   {name: "Pearl Jam"},
                   {name: "Peter Tosh"},
                   {name: "Pink Floyd"},
                   {name: "Planet Hemp"},
                   {name: "R.E.M. Feat. Kate Pearson"},
                   {name: "R.E.M. Feat. KRS-One"},
                   {name: "R.E.M."},
                   {name: "Raimundos"},
                   {name: "Raul Seixas"},
                   {name: "Red Hot Chili Peppers"},
                   {name: "Rush"},
                   {name: "Simply Red"},
                   {name: "Skank"},
                   {name: "Smashing Pumpkins"},
                   {name: "Soundgarden"},
                   {name: "Stevie Ray Vaughan & Double Trouble"},
                   {name: "Stone Temple Pilots"},
                   {name: "System Of A Down"},
                   {name: "Terry Bozzio, Tony Levin & Steve Stevens"},
                   {name: "The Black Crowes"},
                   {name: "The Clash"},
                   {name: "The Cult"},
                   {name: "The Doors"},
                   {name: "The Police"},
                   {name: "The Rolling Stones"},
                   {name: "The Tea Party"},
                   {name: "The Who"},
                   {name: "Tim Maia"},
                   {name: "Tits"},
                   {name: "Battlestar Galactica"},
                   {name: "Heroes"},
                   {name: "Lost"},
                   {name: "U2"},
                   {name: "UB40"},
                   {name: "Van Halen"},
                   {name: "Velvet Revolver"},
                   {name: "Whitesnake"},
                   {name: "Zeca Pagodinho"},
                   {name: "The Office"},
                   {name: "Dread Zeppelin"},
                   {name: "Battlestar Galactica (Classic)"},
                   {name: "Aquaman"},
                   {name: "Christina Aguilera featuring BigElf"},
                   {name: "Aerosmith & Sierra Leone's Refugee Allstars"},
                   {name: "Los Lonely Boys"},
                   {name: "Corinne Bailey Rae"},
                   {name: "Dhani Harrison & Jakob Dylan"},
                   {name: "Jackson Browne"},
                   {name: "Avril Lavigne"},
                   {name: "Big & Rich"},
                   {name: "Youssou N'Dour"},
                   {name: "Black Eyed Peas"},
                   {name: "Jack Johnson"},
                   {name: "Ben Harper"},
                   {name: "Snow Patrol"},
                   {name: "Matisyahu"},
                   {name: "The Postal Service"},
                   {name: "Jaguares"},
                   {name: "The Flaming Lips"},
                   {name: "Jack's Mannequin & Mick Fleetwood"},
                   {name: "Regina Spektor"},
                   {name: "Scorpions"},
                   {name: "House Of Pain"},
                   {name: "Xis"},
                   {name: "Nega Gizza"},
                   {name: "Gustavo & Andres Veiga & Salazar"},
                   {name: "Rodox"},
                   {name: "Charlie Brown Jr."},
                   {name: "Pedro Lus E A Parede"},
                   {name: "Los Hermanos"},
                   {name: "Mundo Livre S/A"},
                   {name: "Otto"},
                   {name: "Instituto"},
                   {name: "Nao Zumbi"},
                   {name: "DJ Dolores & Orchestra Santa Massa"},
                   {name: "Seu Jorge"},
                   {name: "Sabotage E Instituto"},
                   {name: "Stereo Maracana"},
                   {name: "Cake"},
                   {name: "Aisha Duo"},
                   {name: "Habib Koit and Bamada"},
                   {name: "Karsh Kale"},
                   {name: "The Posies"},
                   {name: "Luciana Souza/Romero Lubambo"},
                   {name: "Aaron Goldberg"},
                   {name: "Nicolaus Esterhazy Sinfonia"},
                   {name: "Temple of the Dog"},
                   {name: "Chris Cornell"},
                   {name: "Alberto Turco & Nova Schola Gregoriana"},
                   {name: "Richard Marlow & The Choir of Trinity College, Cambridge"},
                   {name: "English Concert & Trevor Pinnock"},
                   {name: "Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker"},
                   {name: "Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer"},
                   {name: "Wilhelm Kempff"},
                   {name: "Yo-Yo Ma"},
                   {name: "Scholars Baroque Ensemble"},
                   {name: "Academy of St. Martin in the Fields & Sir Neville Marriner"},
                   {name: "Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner"},
                   {name: "Berliner Philharmoniker, Claudio Abbado & Sabine Meyer"},
                   {name: "Royal Philharmonic Orchestra & Sir Thomas Beecham"},
                   {name: "Orchestre Rvolutionnaire et Romantique & John Eliot Gardiner"},
                   {name: "Britten Sinfonia, Ivor Bolton & Lesley Garrett"},
                   {name: "Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti"},
                   {name: "Sir Georg Solti & Wiener Philharmoniker"},
                   {name: "Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair"},
                   {name: "London Symphony Orchestra & Sir Charles Mackerras"},
                   {name: "Barry Wordsworth & BBC Concert Orchestra"},
                   {name: "Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker"},
                   {name: "Eugene Ormandy"},
                   {name: "Luciano Pavarotti"},
                   {name: "Leonard Bernstein & New York Philharmonic"},
                   {name: "Boston Symphony Orchestra & Seiji Ozawa"},
                   {name: "Aaron Copland & London Symphony Orchestra"},
                   {name: "Ton Koopman"},
                   {name: "Sergei Prokofiev & Yuri Temirkanov"},
                   {name: "Chicago Symphony Orchestra & Fritz Reiner"},
                   {name: "Orchestra of The Age of Enlightenment"},
                   {name: "Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra"},
                   {name: "James Levine"},
                   {name: "Berliner Philharmoniker & Hans Rosbaud"},
                   {name: "Maurizio Pollini"},
                   {name: "Academy of St. Martin in the Fields, Sir Neville Marriner & William Bennett"},
                   {name: "Gustav Mahler"},
                   {name: "Felix Schmidt, London Symphony Orchestra & Rafael Frhbeck de Burgos"},
                   {name: "Edo de Waart & San Francisco Symphony"},
                   {name: "Antal Dorti & London Symphony Orchestra"},
                   {name: "Choir Of Westminster Abbey & Simon Preston"},
                   {name: "Michael Tilson Thomas & San Francisco Symphony"},
                   {name: "Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker"},
                   {name: "The King's Singers"},
                   {name: "Berliner Philharmoniker & Herbert Von Karajan"},
                   {name: "Sir Georg Solti, Sumi Jo & Wiener Philharmoniker"},
                   {name: "Christopher O'Riley"},
                   {name: "Fretwork"},
                   {name: "Amy Winehouse"},
                   {name: "Calexico"},
                   {name: "Otto Klemperer & Philharmonia Orchestra"},
                   {name: "Yehudi Menuhin"},
                   {name: "Philharmonia Orchestra & Sir Neville Marriner"},
                   {name: "Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart"},
                   {name: "Les Arts Florissants & William Christie"},
                   {name: "The 12 Cellists of The Berlin Philharmonic"},
                   {name: "Adrian Leaper & Doreen de Feis"},
                   {name: "Roger Norrington, London Classical Players"},
                   {name: "Charles Dutoit & L'Orchestre Symphonique de Montral"},
                   {name: "Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir"},
                   {name: "Kent Nagano and Orchestre de l'Opra de Lyon"},
                   {name: "Julian Bream"},
                   {name: "Martin Roscoe"},
                   {name: "Gteborgs Symfoniker & Neeme Jrvi"},
                   {name: "Itzhak Perlman"},
                   {name: "Michele Campanella"},
                   {name: "Gerald Moore"},
                   {name: "Mela Tenenbaum, Pro Musica Prague & Richard Kapp"},
                   {name: "Emerson String Quartet"},
                   {name: "C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu"},
                   {name: "Nash Ensemble"},
                   {name: "Philip Glass Ensemble"}
               ])
Album.create!([
  {title: "For Those About To Rock We Salute You", artist_id: 1},
  {title: "Balls to the Wall", artist_id: 2},
  {title: "Restless and Wild", artist_id: 2},
  {title: "Let There Be Rock", artist_id: 1},
  {title: "Big Ones", artist_id: 3},
  {title: "Jagged Little Pill", artist_id: 4},
  {title: "Facelift", artist_id: 5},
  {title: "Warner 25 Anos", artist_id: 6},
  {title: "Plays Metallica By Four Cellos", artist_id: 7},
  {title: "Audioslave", artist_id: 8},
  {title: "Out Of Exile", artist_id: 8},
  {title: "BackBeat Soundtrack", artist_id: 9},
  {title: "The Best Of Billy Cobham", artist_id: 10},
  {title: "Alcohol Fueled Brewtality Live! [Disc 1]", artist_id: 11},
  {title: "Alcohol Fueled Brewtality Live! [Disc 2]", artist_id: 11},
  {title: "Black Sabbath", artist_id: 12},
  {title: "Black Sabbath Vol. 4 (Remaster)", artist_id: 12},
  {title: "Body Count", artist_id: 13},
  {title: "Chemical Wedding", artist_id: 14},
  {title: "The Best Of Buddy Guy - The Millenium Collection", artist_id: 15},
  {title: "Prenda Minha", artist_id: 16},
  {title: "Sozinho Remix Ao Vivo", artist_id: 16},
  {title: "Minha Historia", artist_id: 17},
  {title: "Afrociberdelia", artist_id: 18},
  {title: "Da Lama Ao Caos", artist_id: 18},
  {title: "Acstico MTV [Live]", artist_id: 19},
  {title: "Cidade Negra - Hits", artist_id: 19},
  {title: "Na Pista", artist_id: 20},
  {title: "Ax Bahia 2001", artist_id: 21},
  {title: "BBC Sessions [Disc 1] [Live]", artist_id: 22},
  {title: "Bongo Fury", artist_id: 23},
  {title: "Carnaval 2001", artist_id: 21},
  {title: "Chill: Brazil (Disc 1)", artist_id: 24},
  {title: "Chill: Brazil (Disc 2)", artist_id: 6},
  {title: "Garage Inc. (Disc 1)", artist_id: 50},
  {title: "Greatest Hits II", artist_id: 51},
  {title: "Greatest Kiss", artist_id: 52},
  {title: "Heart of the Night", artist_id: 53},
  {title: "International Superhits", artist_id: 54},
  {title: "Into The Light", artist_id: 55},
  {title: "Meus Momentos", artist_id: 56},
  {title: "Minha Histria", artist_id: 57},
  {title: "MK III The Final Concerts [Disc 1]", artist_id: 58},
  {title: "Physical Graffiti [Disc 1]", artist_id: 22},
  {title: "Sambas De Enredo 2001", artist_id: 21},
  {title: "Supernatural", artist_id: 59},
  {title: "The Best of Ed Motta", artist_id: 37},
  {title: "The Essential Miles Davis [Disc 1]", artist_id: 68},
  {title: "The Essential Miles Davis [Disc 2]", artist_id: 68},
  {title: "The Final Concerts (Disc 2)", artist_id: 58},
  {title: "Up An' Atom", artist_id: 69},
  {title: "Vincius De Moraes - Sem Limite", artist_id: 70},
  {title: "Vozes do MPB", artist_id: 21},
  {title: "Chronicle, Vol. 1", artist_id: 76},
  {title: "Chronicle, Vol. 2", artist_id: 76},
  {title: "Cssia Eller - Coleo Sem Limite [Disc 2]", artist_id: 77},
  {title: "Cssia Eller - Sem Limite [Disc 1]", artist_id: 77},
  {title: "Come Taste The Band", artist_id: 58},
  {title: "Deep Purple In Rock", artist_id: 58},
  {title: "Fireball", artist_id: 58},
  {title: "Knocking at Your Back Door: The Best Of Deep Purple in the 80's", artist_id: 58},
  {title: "Machine Head", artist_id: 58},
  {title: "Purpendicular", artist_id: 58},
  {title: "Slaves And Masters", artist_id: 58},
  {title: "Stormbringer", artist_id: 58},
  {title: "The Battle Rages On", artist_id: 58},
  {title: "Vault: Def Leppard's Greatest Hits", artist_id: 78},
  {title: "Outbreak", artist_id: 79},
  {title: "Djavan Ao Vivo - Vol. 02", artist_id: 80},
  {title: "Djavan Ao Vivo - Vol. 1", artist_id: 80},
  {title: "Elis Regina-Minha Histria", artist_id: 41},
  {title: "The Cream Of Clapton", artist_id: 81},
  {title: "Unplugged", artist_id: 81},
  {title: "Album Of The Year", artist_id: 82},
  {title: "Angel Dust", artist_id: 82},
  {title: "King For A Day Fool For A Lifetime", artist_id: 82},
  {title: "The Real Thing", artist_id: 82},
  {title: "Deixa Entrar", artist_id: 83},
  {title: "In Your Honor [Disc 1]", artist_id: 84},
  {title: "In Your Honor [Disc 2]", artist_id: 84},
  {title: "One By One", artist_id: 84},
  {title: "The Colour And The Shape", artist_id: 84},
  {title: "My Way: The Best Of Frank Sinatra [Disc 1]", artist_id: 85},
  {title: "Roda De Funk", artist_id: 86},
  {title: "As Canes de Eu Tu Eles", artist_id: 27},
  {title: "Quanta Gente Veio Ver (Live)", artist_id: 27},
  {title: "Quanta Gente Veio ver--Bnus De Carnaval", artist_id: 27},
  {title: "Faceless", artist_id: 87},
  {title: "American Idiot", artist_id: 54},
  {title: "Appetite for Destruction", artist_id: 88},
  {title: "Use Your Illusion I", artist_id: 88},
  {title: "Use Your Illusion II", artist_id: 88},
  {title: "Blue Moods", artist_id: 89},
  {title: "A Matter of Life and Death", artist_id: 90},
  {title: "A Real Dead One", artist_id: 90},
  {title: "A Real Live One", artist_id: 90},
  {title: "Brave New World", artist_id: 90},
  {title: "Dance Of Death", artist_id: 90},
  {title: "Fear Of The Dark", artist_id: 90},
  {title: "Iron Maiden", artist_id: 90},
  {title: "Killers", artist_id: 90},
  {title: "Live After Death", artist_id: 90},
  {title: "Live At Donington 1992 (Disc 1)", artist_id: 90},
  {title: "Live At Donington 1992 (Disc 2)", artist_id: 90},
  {title: "No Prayer For The Dying", artist_id: 90},
  {title: "Piece Of Mind", artist_id: 90},
  {title: "Powerslave", artist_id: 90},
  {title: "Rock In Rio [CD1]", artist_id: 90},
  {title: "Rock In Rio [CD2]", artist_id: 90},
  {title: "Seventh Son of a Seventh Son", artist_id: 90},
  {title: "Somewhere in Time", artist_id: 90},
  {title: "The Number of The Beast", artist_id: 90},
  {title: "The X Factor", artist_id: 90},
  {title: "Virtual XI", artist_id: 90},
  {title: "Sex Machine", artist_id: 91},
  {title: "Emergency On Planet Earth", artist_id: 92},
  {title: "Synkronized", artist_id: 92},
  {title: "The Return Of The Space Cowboy", artist_id: 92},
  {title: "Get Born", artist_id: 93},
  {title: "Are You Experienced?", artist_id: 94},
  {title: "Surfing with the Alien (Remastered)", artist_id: 95},
  {title: "Jorge Ben Jor 25 Anos", artist_id: 46},
  {title: "Jota Quest-1995", artist_id: 96},
  {title: "Cafezinho", artist_id: 97},
  {title: "Living After Midnight", artist_id: 98},
  {title: "Unplugged [Live]", artist_id: 52},
  {title: "BBC Sessions [Disc 2] [Live]", artist_id: 22},
  {title: "Coda", artist_id: 22},
  {title: "Houses Of The Holy", artist_id: 22},
  {title: "In Through The Out Door", artist_id: 22},
  {title: "IV", artist_id: 22},
  {title: "Led Zeppelin I", artist_id: 22},
  {title: "Led Zeppelin II", artist_id: 22},
  {title: "Led Zeppelin III", artist_id: 22},
  {title: "Physical Graffiti [Disc 2]", artist_id: 22},
  {title: "Presence", artist_id: 22},
  {title: "The Song Remains The Same (Disc 1)", artist_id: 22},
  {title: "The Song Remains The Same (Disc 2)", artist_id: 22},
  {title: "A TempestadeTempestade Ou O Livro Dos Dias", artist_id: 99},
  {title: "Mais Do Mesmo", artist_id: 99},
  {title: "Greatest Hits", artist_id: 100},
  {title: "Lulu Santos - RCA 100 Anos De Msica - lbum 01", artist_id: 101},
  {title: "Lulu Santos - RCA 100 Anos De Msica - lbum 02", artist_id: 101},
  {title: "Misplaced Childhood", artist_id: 102},
  {title: "Barulhinho Bom", artist_id: 103},
  {title: "Seek And Shall Find: More Of The Best (1963-1981)", artist_id: 104},
  {title: "The Best Of Men At Work", artist_id: 105},
  {title: "Black Album", artist_id: 50},
  {title: "Garage Inc. (Disc 2)", artist_id: 50},
  {title: "Kill 'Em All", artist_id: 50},
  {title: "Load", artist_id: 50},
  {title: "Master Of Puppets", artist_id: 50},
  {title: "ReLoad", artist_id: 50},
  {title: "Ride The Lightning", artist_id: 50},
  {title: "St. Anger", artist_id: 50},
  {title: "...And Justice For All", artist_id: 50},
  {title: "Miles Ahead", artist_id: 68},
  {title: "Milton Nascimento Ao Vivo", artist_id: 42},
  {title: "Minas", artist_id: 42},
  {title: "Ace Of Spades", artist_id: 106},
  {title: "Demorou...", artist_id: 108},
  {title: "Motley Crue Greatest Hits", artist_id: 109},
  {title: "From The Muddy Banks Of The Wishkah [Live]", artist_id: 110},
  {title: "Nevermind", artist_id: 110},
  {title: "Compositores", artist_id: 111},
  {title: "Olodum", artist_id: 112},
  {title: "Acstico MTV", artist_id: 113},
  {title: "Arquivo II", artist_id: 113},
  {title: "Arquivo Os Paralamas Do Sucesso", artist_id: 113},
  {title: "Bark at the Moon (Remastered)", artist_id: 114},
  {title: "Blizzard of Ozz", artist_id: 114},
  {title: "Diary of a Madman (Remastered)", artist_id: 114},
  {title: "No More Tears (Remastered)", artist_id: 114},
  {title: "Tribute", artist_id: 114},
  {title: "Walking Into Clarksdale", artist_id: 115},
  {title: "Original Soundtracks 1", artist_id: 116},
  {title: "The Beast Live", artist_id: 117},
  {title: "Live On Two Legs [Live]", artist_id: 118},
  {title: "Pearl Jam", artist_id: 118},
  {title: "Riot Act", artist_id: 118},
  {title: "Ten", artist_id: 118},
  {title: "Vs.", artist_id: 118},
  {title: "Dark Side Of The Moon", artist_id: 120},
  {title: "Os Ces Ladram Mas A Caravana No Pra", artist_id: 121},
  {title: "Greatest Hits I", artist_id: 51},
  {title: "News Of The World", artist_id: 51},
  {title: "Out Of Time", artist_id: 122},
  {title: "Green", artist_id: 124},
  {title: "New Adventures In Hi-Fi", artist_id: 124},
  {title: "The Best Of R.E.M.: The IRS Years", artist_id: 124},
  {title: "Cesta Bsica", artist_id: 125},
  {title: "Raul Seixas", artist_id: 126},
  {title: "Blood Sugar Sex Magik", artist_id: 127},
  {title: "By The Way", artist_id: 127},
  {title: "Californication", artist_id: 127},
  {title: "Retrospective I (1974-1980)", artist_id: 128},
  {title: "Santana - As Years Go By", artist_id: 59},
  {title: "Santana Live", artist_id: 59},
  {title: "Maquinarama", artist_id: 130},
  {title: "O Samba Pocon", artist_id: 130},
  {title: "Judas 0: B-Sides and Rarities", artist_id: 131},
  {title: "Rotten Apples: Greatest Hits", artist_id: 131},
  {title: "A-Sides", artist_id: 132},
  {title: "Morning Dance", artist_id: 53},
  {title: "In Step", artist_id: 133},
  {title: "Core", artist_id: 134},
  {title: "Mezmerize", artist_id: 135},
  {title: "[1997] Black Light Syndrome", artist_id: 136},
  {title: "Live [Disc 1]", artist_id: 137},
  {title: "Live [Disc 2]", artist_id: 137},
  {title: "The Singles", artist_id: 138},
  {title: "Beyond Good And Evil", artist_id: 139},
  {title: "Pure Cult: The Best Of The Cult (For Rockers, Ravers, Lovers & Sinners) [UK]", artist_id: 139},
  {title: "The Doors", artist_id: 140},
  {title: "The Police Greatest Hits", artist_id: 141},
  {title: "Hot Rocks, 1964-1971 (Disc 1)", artist_id: 142},
  {title: "No Security", artist_id: 142},
  {title: "Voodoo Lounge", artist_id: 142},
  {title: "Tangents", artist_id: 143},
  {title: "Transmission", artist_id: 143},
  {title: "My Generation - The Very Best Of The Who", artist_id: 144},
  {title: "Serie Sem Limite (Disc 1)", artist_id: 145},
  {title: "Serie Sem Limite (Disc 2)", artist_id: 145},
  {title: "Acstico", artist_id: 146},
  {title: "Volume Dois", artist_id: 146},
  {title: "Battlestar Galactica: The Story So Far", artist_id: 147},
  {title: "Battlestar Galactica, Season 3", artist_id: 147},
  {title: "Heroes, Season 1", artist_id: 148},
  {title: "Lost, Season 3", artist_id: 149},
  {title: "Lost, Season 1", artist_id: 149},
  {title: "Lost, Season 2", artist_id: 149},
  {title: "Achtung Baby", artist_id: 150},
  {title: "All That You Can't Leave Behind", artist_id: 150},
  {title: "B-Sides 1980-1990", artist_id: 150},
  {title: "How To Dismantle An Atomic Bomb", artist_id: 150},
  {title: "Pop", artist_id: 150},
  {title: "Rattle And Hum", artist_id: 150},
  {title: "The Best Of 1980-1990", artist_id: 150},
  {title: "War", artist_id: 150},
  {title: "Zooropa", artist_id: 150},
  {title: "UB40 The Best Of - Volume Two [UK]", artist_id: 151},
  {title: "Diver Down", artist_id: 152},
  {title: "The Best Of Van Halen, Vol. I", artist_id: 152},
  {title: "Van Halen", artist_id: 152},
  {title: "Van Halen III", artist_id: 152},
  {title: "Contraband", artist_id: 153},
  {title: "Vinicius De Moraes", artist_id: 72},
  {title: "Ao Vivo [IMPORT]", artist_id: 155},
  {title: "The Office, Season 1", artist_id: 156},
  {title: "The Office, Season 2", artist_id: 156},
  {title: "The Office, Season 3", artist_id: 156},
  {title: "Un-Led-Ed", artist_id: 157},
  {title: "Battlestar Galactica (Classic), Season 1", artist_id: 158},
  {title: "Aquaman", artist_id: 159},
  {title: "Instant Karma: The Amnesty International Campaign to Save Darfur", artist_id: 150},
  {title: "Speak of the Devil", artist_id: 114},
  {title: "20th Century Masters - The Millennium Collection: The Best of Scorpions", artist_id: 179},
  {title: "House of Pain", artist_id: 180},
  {title: "Radio Brasil (O Som da Jovem Vanguarda) - Seleccao de Henrique Amaro", artist_id: 36},
  {title: "Cake: B-Sides and Rarities", artist_id: 196},
  {title: "LOST, Season 4", artist_id: 149},
  {title: "Quiet Songs", artist_id: 197},
  {title: "Muso Ko", artist_id: 198},
  {title: "Realize", artist_id: 199},
  {title: "Every Kind of Light", artist_id: 200},
  {title: "Duos II", artist_id: 201},
  {title: "Worlds", artist_id: 202},
  {title: "The Best of Beethoven", artist_id: 203},
  {title: "Temple of the Dog", artist_id: 204},
  {title: "Carry On", artist_id: 205},
  {title: "Revelations", artist_id: 8},
  {title: "Adorate Deum: Gregorian Chant from the Proper of the Mass", artist_id: 206},
  {title: "Allegri: Miserere", artist_id: 207},
  {title: "Pachelbel: Canon & Gigue", artist_id: 208},
  {title: "Vivaldi: The Four Seasons", artist_id: 209},
  {title: "Bach: Violin Concertos", artist_id: 210},
  {title: "Bach: Goldberg Variations", artist_id: 211},
  {title: "Bach: The Cello Suites", artist_id: 212},
  {title: "Handel: The Messiah (Highlights)", artist_id: 213},
  {title: "The World of Classical Favourites", artist_id: 214},
  {title: "Sir Neville Marriner: A Celebration", artist_id: 215},
  {title: "Mozart: Wind Concertos", artist_id: 216},
  {title: "Haydn: Symphonies 99 - 104", artist_id: 217},
  {title: "Beethoven: Symhonies Nos. 5 & 6", artist_id: 218},
  {title: "A Soprano Inspired", artist_id: 219},
  {title: "Great Opera Choruses", artist_id: 220},
  {title: "Wagner: Favourite Overtures", artist_id: 221},
  {title: "Faur: Requiem, Ravel: Pavane & Others", artist_id: 222},
  {title: "Tchaikovsky: The Nutcracker", artist_id: 223},
  {title: "The Last Night of the Proms", artist_id: 224},
  {title: "Puccini: Madama Butterfly - Highlights", artist_id: 225},
  {title: "Holst: The Planets, Op. 32 & Vaughan Williams: Fantasies", artist_id: 226},
  {title: "Pavarotti's Opera Made Easy", artist_id: 227},
  {title: "Great Performances - Barber's Adagio and Other Romantic Favorites for Strings", artist_id: 228},
  {title: "Carmina Burana", artist_id: 229},
  {title: "A Copland Celebration, Vol. I", artist_id: 230},
  {title: "Bach: Toccata & Fugue in D Minor", artist_id: 231},
  {title: "Prokofiev: Symphony No.1", artist_id: 232},
  {title: "Scheherazade", artist_id: 233},
  {title: "Bach: The Brandenburg Concertos", artist_id: 234},
  {title: "Chopin: Piano Concertos Nos. 1 & 2", artist_id: 235},
  {title: "Mascagni: Cavalleria Rusticana", artist_id: 236},
  {title: "Sibelius: Finlandia", artist_id: 237},
  {title: "Beethoven Piano Sonatas: Moonlight & Pastorale", artist_id: 238},
  {title: "Great Recordings of the Century - Mahler: Das Lied von der Erde", artist_id: 240},
  {title: "Elgar: Cello Concerto & Vaughan Williams: Fantasias", artist_id: 241},
  {title: "Adams, John: The Chairman Dances", artist_id: 242},
  {title: "Tchaikovsky: 1812 Festival Overture, Op.49, Capriccio Italien & Beethoven: Wellington's Victory", artist_id: 243},
  {title: "Palestrina: Missa Papae Marcelli & Allegri: Miserere", artist_id: 244},
  {title: "Prokofiev: Romeo & Juliet", artist_id: 245},
  {title: "Strauss: Waltzes", artist_id: 226},
  {title: "Berlioz: Symphonie Fantastique", artist_id: 245},
  {title: "Bizet: Carmen Highlights", artist_id: 246},
  {title: "English Renaissance", artist_id: 247},
  {title: "Handel: Music for the Royal Fireworks (Original Version 1749)", artist_id: 208},
  {title: "Grieg: Peer Gynt Suites & Sibelius: Pellas et Mlisande", artist_id: 248},
  {title: "Mozart Gala: Famous Arias", artist_id: 249},
  {title: "SCRIABIN: Vers la flamme", artist_id: 250},
  {title: "Armada: Music from the Courts of England and Spain", artist_id: 251},
  {title: "Mozart: Symphonies Nos. 40 & 41", artist_id: 248},
  {title: "Back to Black", artist_id: 252},
  {title: "Frank", artist_id: 252},
  {title: "Carried to Dust (Bonus Track Version)", artist_id: 253},
  {title: "Beethoven: Symphony No. 6 'Pastoral' Etc.", artist_id: 254},
  {title: "Bartok: Violin & Viola Concertos", artist_id: 255},
  {title: "Mendelssohn: A Midsummer Night's Dream", artist_id: 256},
  {title: "Bach: Orchestral Suites Nos. 1 - 4", artist_id: 257},
  {title: "Charpentier: Divertissements, Airs & Concerts", artist_id: 258},
  {title: "South American Getaway", artist_id: 259},
  {title: "Grecki: Symphony No. 3", artist_id: 260},
  {title: "Purcell: The Fairy Queen", artist_id: 261},
  {title: "The Ultimate Relexation Album", artist_id: 262},
  {title: "Purcell: Music for the Queen Mary", artist_id: 263},
  {title: "Weill: The Seven Deadly Sins", artist_id: 264},
  {title: "J.S. Bach: Chaconne, Suite in E Minor, Partita in E Major & Prelude, Fugue and Allegro", artist_id: 265},
  {title: "Prokofiev: Symphony No.5 & Stravinksy: Le Sacre Du Printemps", artist_id: 248},
  {title: "Szymanowski: Piano Works, Vol. 1", artist_id: 266},
  {title: "Nielsen: The Six Symphonies", artist_id: 267},
  {title: "Great Recordings of the Century: Paganini's 24 Caprices", artist_id: 268},
  {title: "Liszt - 12 tudes D'Execution Transcendante", artist_id: 269},
  {title: "Great Recordings of the Century - Shubert: Schwanengesang, 4 Lieder", artist_id: 270},
  {title: "Locatelli: Concertos for Violin, Strings and Continuo, Vol. 3", artist_id: 271},
  {title: "Respighi:Pines of Rome", artist_id: 226},
  {title: "Schubert: The Late String Quartets & String Quintet (3 CD's)", artist_id: 272},
  {title: "Monteverdi: L'Orfeo", artist_id: 273},
  {title: "Mozart: Chamber Music", artist_id: 274},
  {title: "Koyaanisqatsi (Soundtrack from the Motion Picture)", artist_id: 275}
])




puts "Data Seeded!"